### PR TITLE
made adjustPipelines.sh work with linux and mac

### PR DESCRIPTION
**Pull request by cdietrich**
[#52]
made adjustPipelines.sh work with linux and mac
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by szarnekow** [comment]
Did not work on my box anymore.

**Comment by cdietrich** [comment]
Hmm what is the error you get?
What is the variable on Mac 
On Travis it seems to work on Mac

**Comment by cdietrich** [comment]
@szarnekow can you have a look at https://github.com/cdietrich/cd-travis-playground

**Comment by szarnekow** [comment]
On my box, it create files with the name pattern  `original.ext''`

**Comment by cdietrich** [comment]
Hmm very strange 
 Ash programming really sucks
And I don’t have a non Travis Mac
At hand for the next days

**Comment by cdietrich** [comment]
And defining aliases seems no to work as well
This I ls why I did it with a variable

**Pull request merged**
