### PR TITLE
Added Gradle Composite. Resolves #1

### LINKED ISSUE #1: Create Gradle Composite

### PR DESCRIPTION
**Pull request by cdietrich**
Added Gradle Composite. Resolves #1

### CODE REVIEW

**Comment by cdietrich** [comment]
@svenefftinge @spoenemann is the structure ok?
@oehme is what i do inside the setting.gradle ok?

**Comment by oehme** [comment]
LGTM

**Comment by kthoms** [comment]
The other Xtext projects use Gradle 3.2. Is it OK to have 3.3 here? Should the other projects be also upgraded?

**Comment by oehme** [comment]
You'll need 3.3 to import composites into Buildship. As long as the nightly works for you, there is no reason against it :)

**Comment by kthoms** [comment]
Looks fine, dependend projects are connected with the composite.

The dependent projects have to change `connection.project.dir`. This must be handled in separate PRs for each repo.

**Pull request merged**
