### PR TITLE
Simrel update job

### PR DESCRIPTION
**Pull request by kthoms**
Makes sure that the build runs with Java 11.

Also introduce a dry-run mode.

### CODE REVIEW

**Comment by Hejado** [comment]
Does not seem to work: https://ci.eclipse.org/xtext/job/releng/job/release-simrel-update/42/console Or am I missing something?

**Comment by kthoms** [comment]
You are missing this comment: https://github.com/eclipse/xtext/issues/1858#issuecomment-723844755

**Comment by kthoms** [comment]
Otherwise I would need to change values to existing, but different URL. It is a bit complicated to change build params with "retry build".
I did this by using "rebuild" to change the parameter, but this overwrites the script. Then I cancelled the build and use "replay".
If you prefer, I could make a build green.

**Comment by Hejado** [comment]
Okay, no need to make it green. M3 will show, let's just try it

**Review by Hejado — APPROVED** [review]

**Pull request merged**
