### PR TITLE
[540593] remove xtext license feature

### PR DESCRIPTION
**Pull request by cdietrich**
[540593] remove xtext license feature

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=540593

**Comment by kthoms** [comment]
I have installed Xtext from the umbrella Jenkins build (the URL did not work for me, I downloaded the zip) with a plain IDE. While installing Xtext I got the license approval dialog. It listed 3 licenses, two of them from Nov 2017.
I guess the change is roughly OK, but I'm wondering what happens rgd. to EPL-2. Platform has chaged to that. I guess it could mean that we might have to refer to a specific version of the license feature. Have to test that.

**Comment by cdietrich** [comment]
wont that require a different org.eclipse.license2 or something like that?

**Comment by cdietrich** [comment]
but indeed https://git.eclipse.org/r/plugins/gitiles/cbi/org.eclipse.license/+/master/org.eclipse.license/
is epl2 now.
i wonder why there are not two of these.
and why mwe uses it without my knowledge or a license change

**Comment by cdietrich** [comment]
that was already done 3 years ago
https://github.com/eclipse/mwe/commit/f44f115fafb300fd871c66ac18a5a02bc97acc66

**Comment by cdietrich** [comment]
=> i assume we have to pick a specific version

**Comment by cdietrich** [comment]
and http://download.eclipse.org/cbi/updates/license/ does not contain any version from 2017

**Comment by cdietrich** [comment]
which then agains leads to ed whining

**Comment by cdietrich** [comment]
@kthoms pinned the version of the feature

**Pull request merged**
