### PR TITLE
[eclipse/xtext#1859] Remove deactivation of Parsley for M1

### PR DESCRIPTION
**Pull request by NicoPrediger**
[eclipse/xtext#1859] Remove deactivation of Parsley for M1

Signed-off-by: Nico Prediger <mail@nicoprediger.de>

### CODE REVIEW

**Review by cdietrich — APPROVED** [review]

**Comment by LorenzoBettini** [comment]
Hi guys.
The deactivation is not required anymore since I removed the upper limit in the version range.

**Comment by cdietrich** [comment]
this is why we remove the adaptation here

**Comment by LorenzoBettini** [comment]
oops, sorry :)

**Comment by NicoPrediger** [comment]
Done in 2.25.0.M1

**Pull request merged**
