### PR TITLE
adapted prefs for latest buildship

### PR DESCRIPTION
**Pull request by cdietrich**
adapted prefs for latest buildship

### CODE REVIEW

**Comment by cdietrich** [comment]
@LorenzoBettini can you check if this file is equals to yours

**Comment by LorenzoBettini** [comment]
@cdietrich mine also has an empty line at the end (it's 16 line long)

**Comment by cdietrich** [comment]
mine has too. no idea where it went. bug in diff view?

**Comment by LorenzoBettini** [comment]
@cdietrich OK, then it's the same file!

**Review by LorenzoBettini — APPROVED** [review]

**Pull request merged**
