### PR TITLE
[eclipse/xtext#1987] move sign-and-deploy away from static pod template

### PR DESCRIPTION
**Pull request by cdietrich**
[eclipse/xtext#1987] move sign-and-deploy away from static pod template

### CODE REVIEW

**Comment by cdietrich** [comment]
unfortunately this does not work yet.
have no idea why we have all these containers in the current one, 
which are still needed, and how to do it with new syntax

**Comment by cdietrich** [comment]
looks better know.
but am not sure how to test all the skipped steps

**Comment by nprediger** [comment]
LGTM

> but am not sure how to test all the skipped steps

Maybe we can run a test release. Alternatively I'd propose to just merge and wait for the real release, fix any problems when & if they come up.

**Review by nprediger — APPROVED** [review]

**Comment by cdietrich** [comment]
i already tested the milestone

**Pull request merged**
